// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlinput

type CreateBoardInput struct {
	Name        string `json:"name"`
	Direction   string `json:"direction"`
	CardsStatus string `json:"cardsStatus"`
}

type CreateCardInput struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	Priority string `json:"priority"`
	DueDate  string `json:"dueDate"`
}

type CreateProjectInput struct {
	LeadID      string    `json:"leadId"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	Members     []*string `json:"members,omitempty"`
	Progress    *int32    `json:"progress,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateBoardInput struct {
	Name        *string `json:"name,omitempty"`
	Direction   *string `json:"direction,omitempty"`
	ThemeColor  *string `json:"themeColor,omitempty"`
	CardsStatus *string `json:"cardsStatus,omitempty"`
}

type UpdateCardInput struct {
	Title     *string  `json:"title,omitempty"`
	Content   *string  `json:"content,omitempty"`
	Status    *string  `json:"status,omitempty"`
	Priority  *string  `json:"priority,omitempty"`
	DueDate   *string  `json:"dueDate,omitempty"`
	Assignees []string `json:"assignees,omitempty"`
}

type UpdateProjectInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	LogoURL     *string `json:"logoUrl,omitempty"`
	Progress    *int32  `json:"progress,omitempty"`
}

type UpdateUserInput struct {
	Name  *string `json:"name,omitempty"`
	Login *string `json:"login,omitempty"`
	Email *string `json:"email,omitempty"`
}
