// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Board struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Direction   string  `json:"direction"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
	ProjectID   string  `json:"projectId"`
	ThemeColor  string  `json:"themeColor"`
	CardsStatus string  `json:"cardsStatus"`
	Cards       []*Card `json:"cards"`
}

type Card struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	Content   string     `json:"content"`
	Priority  string     `json:"priority"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt string     `json:"updatedAt"`
	BoardID   string     `json:"boardId"`
	DueDate   string     `json:"dueDate"`
	Status    string     `json:"status"`
	Assignees []*Member  `json:"assignees"`
	Messages  []*Message `json:"messages"`
}

type CreateBoardInput struct {
	Name        string  `json:"name"`
	Direction   string  `json:"direction"`
	ThemeColor  *string `json:"themeColor,omitempty"`
	CardsStatus string  `json:"cardsStatus"`
}

type CreateCardInput struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	Priority string `json:"priority"`
	DueDate  string `json:"dueDate"`
}

type CreateProjectInput struct {
	LeadID      string    `json:"leadId"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	Members     []*string `json:"members,omitempty"`
	Progress    *int32    `json:"progress,omitempty"`
}

type Member struct {
	ID         string   `json:"id"`
	Role       string   `json:"role"`
	Directions []string `json:"directions"`
	CreatedAt  string   `json:"createdAt"`
	ProjectID  string   `json:"projectId"`
	User       *User    `json:"user"`
}

type Message struct {
	ID        string     `json:"id"`
	Content   string     `json:"content"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt string     `json:"updatedAt"`
	CardID    string     `json:"cardId"`
	Sender    *User      `json:"sender"`
	ReplyTo   *Message   `json:"replyTo,omitempty"`
	Replies   []*Message `json:"replies"`
}

type Mutation struct {
}

type Project struct {
	ID          string    `json:"id"`
	CreatedAt   string    `json:"createdAt"`
	UpdatedAt   string    `json:"updatedAt"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	LogoURL     string    `json:"logoUrl"`
	Progress    int32     `json:"progress"`
	Lead        *Member   `json:"lead"`
	Members     []*Member `json:"members"`
	Boards      []*Board  `json:"boards"`
}

type Query struct {
}

type Schema struct {
	ID        string  `json:"id"`
	Direction *string `json:"direction,omitempty"`
	URL       string  `json:"url"`
	Name      string  `json:"name"`
	Author    *Member `json:"author"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type UpdateBoardInput struct {
	Name        *string `json:"name,omitempty"`
	Direction   *string `json:"direction,omitempty"`
	ThemeColor  *string `json:"themeColor,omitempty"`
	CardsStatus *string `json:"cardsStatus,omitempty"`
}

type UpdateCardInput struct {
	Title     *string  `json:"title,omitempty"`
	Content   *string  `json:"content,omitempty"`
	Status    *string  `json:"status,omitempty"`
	Priority  *string  `json:"priority,omitempty"`
	DueDate   *string  `json:"dueDate,omitempty"`
	Assignees []string `json:"assignees,omitempty"`
}

type UpdateProjectInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	LogoURL     *string `json:"logoUrl,omitempty"`
	Progress    *int32  `json:"progress,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	AvatarURL string `json:"avatarUrl"`
	Login     string `json:"login"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	CreatedAt string `json:"createdAt"`
}
